# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-12-06 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoadon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonggia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ngaylap', models.DateTimeField(auto_now=True)),
                ('trangthai', models.IntegerField(choices=[(0, 'Cancel'), (1, 'Success'), (2, 'Processing')], default=2)),
                ('locked', models.BooleanField(choices=[(True, 'Lock'), (False, 'UnLock')], default=False)),
                ('ghichu', models.TextField()),
            ],
            options={
                'db_table': 'hoadon',
            },
        ),
        migrations.CreateModel(
            name='hoadonchitiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('locked', models.BooleanField(choices=[(True, 'Lock'), (False, 'UnLock')], default=False)),
                ('mahoadon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hoadon')),
            ],
            options={
                'db_table': 'hoadonchitiet',
            },
        ),
        migrations.CreateModel(
            name='ketnoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlan', models.CharField(max_length=100)),
                ('bluetooth', models.CharField(max_length=100)),
                ('gps', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ketnoi',
            },
        ),
        migrations.CreateModel(
            name='phieunhap',
            fields=[
                ('imei_may', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ngaylap', models.DateTimeField(auto_now=True)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('locked', models.BooleanField(choices=[(True, 'Lock'), (False, 'UnLock')], default=False)),
                ('ghichu', models.TextField()),
            ],
            options={
                'db_table': 'phieunhap',
            },
        ),
        migrations.CreateModel(
            name='phieuxuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaylap', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(choices=[(True, 'Lock'), (False, 'UnLock')], default=False)),
                ('ghichu', models.TextField()),
                ('mahoadon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hoadon')),
            ],
            options={
                'db_table': 'phieuxuat',
            },
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensp', models.CharField(max_length=200)),
                ('kichthuocman', models.CharField(max_length=100)),
                ('thongsoman', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('kichthuoc', models.CharField(max_length=100)),
                ('khoiluong', models.CharField(max_length=100)),
                ('thoidiemramat', models.DateField()),
                ('chipset', models.CharField(max_length=100)),
                ('tscpu', models.CharField(max_length=100)),
                ('bonhoram', models.CharField(max_length=100)),
                ('hedieuhanh', models.CharField(max_length=100)),
                ('baomatvantay', models.CharField(max_length=100)),
                ('chongnuoc', models.CharField(max_length=100)),
                ('dongsp_catalog', models.CharField(max_length=100)),
                ('ketnoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ketnoi')),
            ],
            options={
                'db_table': 'sanpham',
            },
        ),
        migrations.CreateModel(
            name='sanphamtuychon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(default=0)),
                ('giasanpham', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anhdaidien', models.ImageField(upload_to='pic_folder')),
                ('locked', models.BooleanField(choices=[(True, 'Lock'), (False, 'UnLock')], default=False)),
                ('ma_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
            options={
                'db_table': 'sanphamtuychon',
            },
        ),
        migrations.CreateModel(
            name='taikhoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('hovaten', models.CharField(max_length=100)),
                ('sinhnhat', models.DateField()),
                ('gioitinh', models.BooleanField()),
                ('sodienthoai', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('diachi', models.TextField()),
                ('loaitaikhoan', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'taikhoan',
            },
        ),
        migrations.CreateModel(
            name='thongsocamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemanh', models.CharField(max_length=100)),
                ('thongsocoban', models.CharField(max_length=100)),
                ('dacdiem', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'thongsocamera',
            },
        ),
        migrations.CreateModel(
            name='tuychon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mausac', models.CharField(max_length=100)),
                ('bonhotrong', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tuychon',
            },
        ),
        migrations.CreateModel(
            name='kho',
            fields=[
                ('imei_may', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.phieunhap')),
                ('trangthaiban', models.BooleanField()),
            ],
            options={
                'db_table': 'kho',
            },
        ),
        migrations.AddField(
            model_name='sanphamtuychon',
            name='ma_tuy_chon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuychon'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='macamerasau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_sau', to='app.thongsocamera'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='macameratruoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_truoc', to='app.thongsocamera'),
        ),
        migrations.AddField(
            model_name='phieuxuat',
            name='manguoilap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taikhoan'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='masanphamtuychon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanphamtuychon'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='usernhanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taikhoan'),
        ),
        migrations.AddField(
            model_name='hoadonchitiet',
            name='masanphamtuychon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanphamtuychon'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='user_khachhang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khachhang', to='app.taikhoan'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='usernhanvien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhanvien', to='app.taikhoan'),
        ),
        migrations.AddField(
            model_name='phieuxuat',
            name='imei_may',
            field=models.ForeignKey(on_delete=models.Model, to='app.kho'),
        ),
        migrations.AddField(
            model_name='kho',
            name='masanphamtuychon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanphamtuychon'),
        ),
    ]
